/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import DAO.ClienteDAO;
import Modelo.Cliente;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class Pesquisa_Cliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form Pesquisa_Cliente
     */
    DefaultTableModel tmCliente = new DefaultTableModel(null, new String[]{"Nome", "Pessoa", "CPF - CNPJ", "Telefone (1)", "Telefone (2)", "Celular (1)", "Celular (2)", "Email", "Endereço", "CEP"});
    List<Cliente> clientes;
    ListSelectionModel lsmCliente;

    public Pesquisa_Cliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Tabela = new javax.swing.JTable();
        jLCabecalho = new javax.swing.JLabel();
        jTNome = new javax.swing.JTextField();
        jTCPF = new javax.swing.JTextField();
        jLNome = new javax.swing.JLabel();
        jLCPF = new javax.swing.JLabel();
        jBPesquisar = new javax.swing.JButton();

        setClosable(true);

        Tabela.setModel(tmCliente);
        jScrollPane1.setViewportView(Tabela);

        jLCabecalho.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLCabecalho.setText("Pesquisa de Clientes");

        jTNome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTCPF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLNome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLNome.setText("Nome:");

        jLCPF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLCPF.setText("CPF - CNPJ:");

        jBPesquisar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jBPesquisar.setText("Pesquisar");
        jBPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 991, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLNome)
                                .addGap(18, 18, 18)
                                .addComponent(jTNome, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(jLCPF)
                                .addGap(18, 18, 18)
                                .addComponent(jTCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBPesquisar))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(396, 396, 396)
                        .addComponent(jLCabecalho)))
                .addContainerGap(183, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLCabecalho)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNome)
                    .addComponent(jTNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLCPF)
                    .addComponent(jTCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBPesquisar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPesquisarActionPerformed
        try {
            if ((!jTNome.getText().equals("")) && (!jTCPF.getText().equals(""))) {
                JOptionPane.showMessageDialog(null, "Por favor, Apenas um campo deve ser preenchido!");
            } else if (jTNome.getText().equals("")) {
                ClienteDAO cdao = new ClienteDAO();
                clientes = cdao.listarCPF("%" + jTCPF.getText() + "%");
                String endereco;

                while (tmCliente.getRowCount() > 0) {
                    tmCliente.removeRow(0);
                }

                String[] linha = new String[]{null, null, null, null};
                for (int i = 0; i < clientes.size(); i++) {
                    endereco = clientes.get(i).getRua() + " " + clientes.get(i).getNumero() + ", " + clientes.get(i).getBairro() + " - " + clientes.get(i).getCidade();
                    tmCliente.addRow(linha);
                    tmCliente.setValueAt(clientes.get(i).getNome(), i, 0);
                    tmCliente.setValueAt(clientes.get(i).getPessoa(), i, 1);
                    tmCliente.setValueAt(clientes.get(i).getCpf_cnpj(), i, 2);
                    tmCliente.setValueAt(clientes.get(i).getTelefone1(), i, 3);
                    tmCliente.setValueAt(clientes.get(i).getTelefone2(), i, 4);
                    tmCliente.setValueAt(clientes.get(i).getCelular1(), i, 5);
                    tmCliente.setValueAt(clientes.get(i).getCelular2(), i, 6);
                    tmCliente.setValueAt(clientes.get(i).getEmail(), i, 7);
                    tmCliente.setValueAt(endereco, i, 8);
                    tmCliente.setValueAt(clientes.get(i).getCep(), i, 9);
                }
            } else if (jTCPF.getText().equals("")) {
                ClienteDAO cdao = new ClienteDAO();
                clientes = cdao.listarNome("%" + jTNome.getText() + "%");
                String endereco;

                while (tmCliente.getRowCount() > 0) {
                    tmCliente.removeRow(0);
                }

                String[] linha = new String[]{null, null, null, null};
                for (int i = 0; i < clientes.size(); i++) {
                    endereco = clientes.get(i).getRua() + " " + clientes.get(i).getNumero() + ", " + clientes.get(i).getBairro() + " - " + clientes.get(i).getCidade();
                    tmCliente.addRow(linha);
                    tmCliente.setValueAt(clientes.get(i).getNome(), i, 0);
                    tmCliente.setValueAt(clientes.get(i).getPessoa(), i, 1);
                    tmCliente.setValueAt(clientes.get(i).getCpf_cnpj(), i, 2);
                    tmCliente.setValueAt(clientes.get(i).getTelefone1(), i, 3);
                    tmCliente.setValueAt(clientes.get(i).getTelefone2(), i, 4);
                    tmCliente.setValueAt(clientes.get(i).getCelular1(), i, 5);
                    tmCliente.setValueAt(clientes.get(i).getCelular2(), i, 6);
                    tmCliente.setValueAt(clientes.get(i).getEmail(), i, 7);
                    tmCliente.setValueAt(endereco, i, 8);
                    tmCliente.setValueAt(clientes.get(i).getCep(), i, 9);
                }
            }


        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jBPesquisarActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabela;
    private javax.swing.JButton jBPesquisar;
    private javax.swing.JLabel jLCPF;
    private javax.swing.JLabel jLCabecalho;
    private javax.swing.JLabel jLNome;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTCPF;
    private javax.swing.JTextField jTNome;
    // End of variables declaration//GEN-END:variables
}
