/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import DAO.ClienteDAO;
import DAO.ProdutoDAO;
import DAO.VendaDAO;
import Jasper.JasperReport;
import Modelo.Cliente;
import Modelo.Produto;
import Modelo.Venda;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;

/**
 *
 * @author user
 */
public class Venda_Produto extends javax.swing.JInternalFrame {

    /**
     * Creates new form Venda_Produto
     */
    double total = 0;
    Produto produto;
    DefaultTableModel tmCliente = new DefaultTableModel(null, new String[]{"Nome", "CPF - CNPJ", "Endereço", "Telefone", "Pessoa"});
    List<Cliente> clientes;
    ListSelectionModel lsmCliente;
    DefaultTableModel tmProduto = new DefaultTableModel(null, new String[]{"Código", "Produto", "Qnt", "Valor", "Total do Produto"});
    List<Produto> produtos = new ArrayList<>();
    ListSelectionModel lsmProduto;

    public Venda_Produto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTCliente = new javax.swing.JTextField();
        jLCabecalho = new javax.swing.JLabel();
        jLCliente = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaCliente = new javax.swing.JTable();
        jBPesquisar = new javax.swing.JButton();
        jBProduto = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TabelaProduto = new javax.swing.JTable();
        jLTotal = new javax.swing.JLabel();
        jTTotal = new javax.swing.JTextField();
        jBEfetuarVenda = new javax.swing.JButton();
        jBCancelar = new javax.swing.JButton();
        jBRomaneio = new javax.swing.JButton();
        jLCodigo = new javax.swing.JLabel();
        jLQuantidade = new javax.swing.JLabel();
        jTCodigo = new javax.swing.JTextField();
        jTQnt = new javax.swing.JTextField();

        setClosable(true);

        jTCliente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLCabecalho.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLCabecalho.setText("Venda - Produtos");

        jLCliente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLCliente.setText("Cliente:");

        TabelaCliente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TabelaCliente.setModel(tmCliente);
        TabelaCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaClienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelaCliente);

        jBPesquisar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jBPesquisar.setText("Pesquisar");
        jBPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPesquisarActionPerformed(evt);
            }
        });

        jBProduto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jBProduto.setText("ADD PRODUTO");
        jBProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBProdutoActionPerformed(evt);
            }
        });

        TabelaProduto.setModel(tmProduto);
        jScrollPane2.setViewportView(TabelaProduto);

        jLTotal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLTotal.setText("Total:");

        jTTotal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jBEfetuarVenda.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jBEfetuarVenda.setText("Efetuar Venda");
        jBEfetuarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEfetuarVendaActionPerformed(evt);
            }
        });

        jBCancelar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jBCancelar.setText("Cancelar Venda");
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });

        jBRomaneio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jBRomaneio.setText("Gerar Romaneio");
        jBRomaneio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRomaneioActionPerformed(evt);
            }
        });

        jLCodigo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLCodigo.setText("Código:");

        jLQuantidade.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLQuantidade.setText("Quantidade:");

        jTCodigo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTQnt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(476, 476, 476)
                        .addComponent(jLTotal)
                        .addGap(18, 18, 18)
                        .addComponent(jTTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLCliente)
                                .addGap(18, 18, 18)
                                .addComponent(jTCliente)
                                .addGap(18, 18, 18)
                                .addComponent(jBPesquisar))
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBProduto)
                                .addGap(18, 18, 18)
                                .addComponent(jLCodigo)
                                .addGap(18, 18, 18)
                                .addComponent(jTCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(jLQuantidade)
                                .addGap(18, 18, 18)
                                .addComponent(jTQnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(50, 50, 50))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(jLCabecalho))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jBRomaneio)
                        .addGap(38, 38, 38)
                        .addComponent(jBEfetuarVenda)
                        .addGap(41, 41, 41)
                        .addComponent(jBCancelar)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jBCancelar, jBEfetuarVenda, jBRomaneio});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTCodigo, jTQnt});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLCabecalho)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLCliente)
                    .addComponent(jBPesquisar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBProduto)
                    .addComponent(jLCodigo)
                    .addComponent(jLQuantidade)
                    .addComponent(jTCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTQnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLTotal)
                    .addComponent(jTTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBEfetuarVenda)
                    .addComponent(jBCancelar)
                    .addComponent(jBRomaneio))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPesquisarActionPerformed
        try {
            ClienteDAO cdao = new ClienteDAO();
            clientes = cdao.listarNome("%" + jTCliente.getText() + "%");
            String endereco;

            while (tmCliente.getRowCount() > 0) {
                tmCliente.removeRow(0);
            }

            String[] linha = new String[]{null, null, null, null};
            for (int i = 0; i < clientes.size(); i++) {
                endereco = clientes.get(i).getRua() + " " + clientes.get(i).getNumero() + ", " + clientes.get(i).getBairro() + " - " + clientes.get(i).getCidade();
                tmCliente.addRow(linha);
                tmCliente.setValueAt(clientes.get(i).getNome(), i, 0);
                tmCliente.setValueAt(clientes.get(i).getCpf_cnpj(), i, 1);
                tmCliente.setValueAt(endereco, i, 2);
                tmCliente.setValueAt(clientes.get(i).getTelefone1(), i, 3);
                tmCliente.setValueAt(clientes.get(i).getPessoa(), i, 4);
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jBPesquisarActionPerformed

    private void TabelaClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaClienteMouseClicked
        jTCliente.setText(clientes.get(TabelaCliente.getSelectedRow()).getNome());
    }//GEN-LAST:event_TabelaClienteMouseClicked

    private void jBProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBProdutoActionPerformed
        try {
            ProdutoDAO pdao = new ProdutoDAO();
            produto = pdao.addProduto(jTCodigo.getText());
            produto.setQuant_itens(Double.parseDouble(jTQnt.getText()));
            produto.setValor_venda(produto.getValor_venda() * produto.getQuant_itens());
            produtos.add(produto);

            while (tmProduto.getRowCount() > 0) {
                tmProduto.removeRow(0);
            }

            String[] linha = new String[]{null, null, null, null};
            double totalP = produto.getValor_venda();
            for (int i = 0; i < produtos.size(); i++) {
                tmProduto.addRow(linha);
                tmProduto.setValueAt(produtos.get(i).getCodigo(), i, 0);
                tmProduto.setValueAt(produtos.get(i).getNome(), i, 1);
                tmProduto.setValueAt(produtos.get(i).getQuant_itens(), i, 2);
                tmProduto.setValueAt(format(produtos.get(i).getValor_venda() / produtos.get(i).getQuant_itens()), i, 3);
                tmProduto.setValueAt(format(produtos.get(i).getValor_venda()), i, 4);
            }
            total = total + totalP;
            jTTotal.setText(format(total));
        } catch (SQLException ex) {
            Logger.getLogger(Venda_Produto.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jBProdutoActionPerformed

    private void jBEfetuarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEfetuarVendaActionPerformed
        if (((jTCliente.getText().equals("") || jTCodigo.getText().equals("") || jTQnt.getText().equals("")))) {
            JOptionPane.showMessageDialog(null, "Por favor preenxa todos os dados!");
        } else {
            try {
                VendaDAO vdao = new VendaDAO();
                Venda venda = new Venda();
                Cliente cliente = new Cliente();
                cliente.setCodigo(clientes.get(TabelaCliente.getSelectedRow()).getCodigo());
                venda.setCliente(cliente);
                venda.setProduto(produto);
                venda.setValor_total(total);
                venda.setCodigo(vdao.PegarId());

                for (int i = 0; i < produtos.size(); i++) {
                    venda.setValor_produto(produtos.get(i).getValor_venda() / produtos.get(i).getQuant_itens());
                    venda.setProduto(produtos.get(i));
                    vdao.adicionar(venda);
                }
                JOptionPane.showMessageDialog(null, "Venda efetuada com sucesso!");
            } catch (SQLException ex) {
                Logger.getLogger(Venda_Produto.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jBEfetuarVendaActionPerformed

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        jTCliente.setText("");
        jTCodigo.setText("");
        jTQnt.setText("");
        jTTotal.setText("");

        while (tmProduto.getRowCount() > 0) {
            tmProduto.removeRow(0);
        }
        while (tmCliente.getRowCount() > 0) {
            tmCliente.removeRow(0);
        }
        produto = null;
        produtos = null;

    }//GEN-LAST:event_jBCancelarActionPerformed

    private void jBRomaneioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRomaneioActionPerformed
        try {
            VendaDAO vdao = new VendaDAO();
            JasperReport jasper = new JasperReport();
            jasper.gerar(vdao.PegarId() - 1, clientes.get(TabelaCliente.getSelectedRow()).getCodigo());
        } catch (JRException ex) {
            Logger.getLogger(Venda_Produto.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Venda_Produto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBRomaneioActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabelaCliente;
    private javax.swing.JTable TabelaProduto;
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBEfetuarVenda;
    private javax.swing.JButton jBPesquisar;
    private javax.swing.JButton jBProduto;
    private javax.swing.JButton jBRomaneio;
    private javax.swing.JLabel jLCabecalho;
    private javax.swing.JLabel jLCliente;
    private javax.swing.JLabel jLCodigo;
    private javax.swing.JLabel jLQuantidade;
    private javax.swing.JLabel jLTotal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTCliente;
    private javax.swing.JTextField jTCodigo;
    private javax.swing.JTextField jTQnt;
    private javax.swing.JTextField jTTotal;
    // End of variables declaration//GEN-END:variables

    public static String format(double x) {
        return String.format("R$ %.2f", x);
    }
}
